stages:
   - pre-build
   - build

# Build
clone-product-config:
  stage: pre-build
  image:
        name: alpine/git:latest
        entrypoint: [""]
  script:
    - git clone https://$GITLAB_LOGIN_USER_NAME:$GITLAB_ACCESS_TOKEN@gitlab.cpicloudservices.com/engineering/easitrax-connect/swc/product-config.git
  artifacts:
    paths:
      - product-config
    expire_in: 1 day
  only:
    - branches

Build:
  image: mcr.microsoft.com/dotnet/framework/sdk
  stage: build
  script:
    - Get-Location
    - echo Ok
    
    - Copy-Item -Path product-config\NugetConfig\nuget.config -Destination .

    - Get-ChildItem -Path . -Recurse -Include nuget.config | % {(Get-Content $_.fullName).replace("SharedPackages", "ec-etito_export\Ec.Bvlive.ExportETicket\packages") | Set-Content $_.fullName}
    - Get-ChildItem -Path . -Recurse -Include nuget.config | % {(Get-Content $_.fullName).replace($STYLESOFT_NUGET_SOURCE, $EASITRAX_PROGET_NUGET_SOURCE) | Set-Content $_.fullName}

    - dotnet restore Ec.Bvlive.ExportETicket\Ec.Bvlive.ExportETicket.sln
    - nuget restore Ec.Bvlive.ExportETicket\Ec.Bvlive.ExportETicket.sln
    - msbuild Ec.Bvlive.ExportETicket\Ec.Bvlive.ExportETicket.sln /p:Configuration=Release
    
    - New-Item -ItemType "directory" -Path "artifacts"
    - Move-Item -Path Ec.Bvlive.ExportETicket\Ec.Bvlive.ExportETicket\bin\Release -Destination artifacts

  only:
    - branches
  tags:
    - windows-runner
  artifacts:
    paths:
        - artifacts